import {
  UserProfile,
  StudentProfile,
  SkillItem,
  ProjectItem,
  AchievementItem,
  CareerGoalItem,
} from '../types';

export const DEMO_USER_PROFILE: UserProfile = {
  id: 'demo-creator-showcase',
  email: 'vangalasricharan7@gmail.com',
  fullName: 'Sricharan Vangala',
  university: 'Marwadi University',
  degree: 'B.Tech',
  branch: 'Computer Science & Engineering (AI/ML)',
  program: 'B.Tech Computer Science & Engineering (AI/ML)',
  year: '2nd Year',
  expectedGraduationYear: '2027',
  careerGoal: 'AI/ML Engineer',
  targetRole: 'AI/ML Engineer',
  currentSkills: 'Python, PyTorch, Transformers, TypeScript, React, Scikit-Learn, Vector DB, FastAPI, Supabase, LLM Agents',
  skills: [
    'Python',
    'PyTorch',
    'Transformers',
    'TypeScript',
    'React',
    'Scikit-Learn',
    'Vector DB',
    'FastAPI',
    'Supabase',
    'LLM Agents',
  ],
  bio: 'Student engineer at Marwadi University specializing in AI/ML systems, Generative AI agent architectures, and career intelligence ontologies.',
  githubUrl: 'https://github.com/Sricharan-Vangala',
  linkedinUrl: 'https://linkedin.com/in/sricharan-vangala',
  phone: '+91 85209 81574',
  location: 'Gujarat, India',
  plan: 'pro',
  subscriptionStatus: 'active',
  isOnboarded: true,
  createdAt: '2024-01-15T00:00:00.000Z',
  isDemo: true,
};

export const DEMO_STUDENT_PROFILES: StudentProfile[] = [
  {
    id: 'demo-student-sricharan',
    userId: 'demo-creator-showcase',
    name: 'Sricharan Vangala',
    university: 'Marwadi University',
    degree: 'B.Tech',
    branch: 'Computer Science & Engineering (AI/ML)',
    year: '2nd Year',
    expectedGraduationYear: '2027',
    careerGoal: 'AI/ML Engineer',
    targetRole: 'AI/ML Engineer',
    currentSkills: 'Python, PyTorch, Transformers, TypeScript, React, Scikit-Learn, Vector DB, FastAPI, Supabase, LLM Agents',
    bio: 'Student engineer at Marwadi University specializing in AI/ML systems, Generative AI agent architectures, and career intelligence ontologies.',
    githubUrl: 'https://github.com/Sricharan-Vangala',
    linkedinUrl: 'https://linkedin.com/in/sricharan-vangala',
    isActive: true,
    profileData: {
      bio: 'Student engineer at Marwadi University specializing in AI/ML systems, Generative AI agent architectures, and career intelligence ontologies.',
      githubUrl: 'https://github.com/Sricharan-Vangala',
      linkedinUrl: 'https://linkedin.com/in/sricharan-vangala',
      phone: '+91 85209 81574',
      location: 'Gujarat, India',
    },
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
];

export const DEMO_SKILLS: SkillItem[] = [
  {
    id: 'demo-skill-1',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Python',
    category: 'Programming',
    proficiency: 'Expert',
    score: 95,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-2',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'PyTorch',
    category: 'AI/ML',
    proficiency: 'Advanced',
    score: 90,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-3',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Transformers & NLP',
    category: 'AI/ML',
    proficiency: 'Advanced',
    score: 88,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-4',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Generative AI & LLM Agents',
    category: 'AI/ML',
    proficiency: 'Advanced',
    score: 92,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-5',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'TypeScript',
    category: 'Programming',
    proficiency: 'Advanced',
    score: 90,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-6',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'React',
    category: 'Web Development',
    proficiency: 'Advanced',
    score: 88,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-7',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'FastAPI',
    category: 'Web Development',
    proficiency: 'Intermediate',
    score: 85,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-8',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'PostgreSQL & Supabase',
    category: 'Databases',
    proficiency: 'Advanced',
    score: 86,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-9',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Vector DB & Embeddings',
    category: 'Databases',
    proficiency: 'Intermediate',
    score: 84,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-10',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'DSA & Graph Algorithms',
    category: 'DSA',
    proficiency: 'Advanced',
    score: 88,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-11',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Git & CI/CD Pipelines',
    category: 'Tools',
    proficiency: 'Advanced',
    score: 90,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-12',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Deep Learning & Math Foundations',
    category: 'AI/ML',
    proficiency: 'Advanced',
    score: 90,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
];

export const DEMO_PROJECTS: ProjectItem[] = [
  {
    id: 'demo-proj-sdt',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Student Digital Twin OS',
    description:
      'Continuous student career readiness operating system synthesizing academic trajectory, project proofs, and market qualification models with automated ATS auditing and repository telemetry.',
    architecture:
      'Modular React + TypeScript client with Tailwind CSS, Supabase PostgreSQL data persistence, Google Gemini API intelligence layer, and graph ontology models.',
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Supabase', 'Gemini AI', 'Graph Ontologies'],
    githubUrl: 'https://github.com/Sricharan-Vangala/student-digital-twin',
    liveDemoUrl: 'https://student-digital-twin.vercel.app',
    role: 'Founder & Lead Architect',
    difficulty: 'Production',
    status: 'Completed',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-proj-agent',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Autonomous LLM Agent Pipeline',
    description:
      'Deep reasoning agentic pipeline executing multi-step retrieval, code execution verification, and structured report synthesis.',
    architecture:
      'FastAPI microservice backend with PyTorch embeddings, Pinecone vector indexing, tool calling orchestration, and Docker deployment.',
    techStack: ['Python', 'PyTorch', 'Transformers', 'FastAPI', 'Pinecone', 'Docker'],
    githubUrl: 'https://github.com/Sricharan-Vangala/autonomous-llm-agent',
    liveDemoUrl: 'https://github.com/Sricharan-Vangala/autonomous-llm-agent',
    role: 'AI/ML Engineer',
    difficulty: 'Advanced',
    status: 'Completed',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-proj-graph',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Neural Graph Academic Knowledge Engine',
    description:
      'Dynamic knowledge graph system mapping university academic syllabi to high-demand industry skill clusters and placement competencies.',
    architecture:
      'NetworkX and PyTorch Geometric graph embeddings mapped to Neo4j knowledge triples with semantic similarity scoring.',
    techStack: ['Python', 'NetworkX', 'PyTorch Geometric', 'Neo4j', 'Scikit-Learn'],
    githubUrl: 'https://github.com/Sricharan-Vangala/neural-graph-knowledge',
    liveDemoUrl: 'https://github.com/Sricharan-Vangala/neural-graph-knowledge',
    role: 'Lead Developer',
    difficulty: 'Advanced',
    status: 'Completed',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-proj-resume',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'ATS Smart Resume Optimizer & Placement Simulator',
    description:
      'Deterministic parser and semantic embedding scorer analyzing technical resumes against role benchmarks with real-time actionable feedback.',
    architecture:
      'Client-side PDF text extraction and semantic keyword density matcher with structured scoring algorithms.',
    techStack: ['TypeScript', 'React', 'Node.js', 'NLP Embeddings', 'Tailwind CSS'],
    githubUrl: 'https://github.com/Sricharan-Vangala/ats-resume-optimizer',
    liveDemoUrl: 'https://github.com/Sricharan-Vangala/ats-resume-optimizer',
    role: 'Full Stack AI Developer',
    difficulty: 'Intermediate',
    status: 'Completed',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
];

export const DEMO_ACHIEVEMENTS: AchievementItem[] = [
  {
    id: 'demo-ach-1',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Built and Launched Student Digital Twin OS',
    organization: 'Marwadi University Showcase & Open Source',
    date: '2024-02-01',
    description:
      'Designed and deployed full-stack Student Digital Twin platform empowering engineering students with AI-driven readiness telemetry.',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-ach-2',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Marwadi University Top Tech Innovator Recognition',
    organization: 'Marwadi University Department of CSE',
    date: '2024-01-10',
    description:
      'Recognized for exceptional engineering projects in generative AI systems and student career readiness tools.',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-ach-3',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Deep Learning Specialization Certified',
    organization: 'DeepLearning.AI & Coursera',
    date: '2023-11-20',
    description:
      'Mastered neural network architectures, hyperparameter tuning, sequence models, and deep learning math foundations.',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-ach-4',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Open Source AI Contributor & Project Lead',
    organization: 'GitHub Community',
    date: '2024-03-01',
    description:
      'Published open-source AI tooling, autonomous agent prototypes, and automated evaluation frameworks.',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
];

export const DEMO_CAREER_GOALS: CareerGoalItem[] = [
  {
    id: 'demo-goal-1',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    goal: 'Become a Principal AI/ML Engineer & Systems Architect',
    targetRole: 'AI/ML Engineer',
    targetCompanies: ['Google', 'DeepMind', 'Microsoft', 'OpenAI', 'Top Tech Startups'],
    requiredSkills: [
      'PyTorch',
      'Distributed Machine Learning',
      'LLM Reasoning',
      'System Design',
      'Vector Ontologies',
    ],
    timeline: 'By 2027 (Expected Graduation)',
    isActive: true,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
];
