import {
  UserProfile,
  StudentProfile,
  SkillItem,
  ProjectItem,
  AchievementItem,
  CareerGoalItem,
  UserPortfolioRecord,
} from '../types';

export const DEMO_PORTFOLIO_RECORD: UserPortfolioRecord = {
  portfolioType: 'external',
  externalUrl: 'https://vangala-sricharan-portfolio.vercel.app/',
  generatedPortfolio: {
    theme: 'modern-minimal',
    hero: {
      name: 'Sricharan Vangala',
      tagline: 'AI/ML Systems Engineer & Generative AI Architect',
      location: 'Gujarat, India',
      bio: 'Engineering high-throughput LLM agents, neural search systems, and deterministic career operating systems at Marwadi University.',
      availableForRoles: ['AI/ML Engineer', 'Generative AI Engineer', 'Backend ML Systems Intern'],
      avatarUrl: '',
    },
    about: {
      summary: 'Passionate computer science student specializing in Machine Learning and Generative AI systems. Proven experience designing agent architectures, vector indexing pipelines, and real-time career intelligence platforms.',
      education: {
        university: 'Marwadi University',
        degree: 'B.Tech',
        branch: 'Computer Science & Engineering (AI/ML)',
        year: '2nd Year',
        graduationYear: '2027',
      },
      careerAspirations: 'Aiming to build foundational AI infrastructures and scalable cognitive agent frameworks at world-class research and technology institutions.',
    },
    skills: [
      {
        category: 'AI / Machine Learning',
        items: ['PyTorch', 'Transformers & NLP', 'Generative AI & LLM Agents', 'Scikit-Learn', 'Vector DB & Embeddings'],
      },
      {
        category: 'Software Engineering',
        items: ['Python', 'TypeScript', 'React 18+', 'FastAPI', 'Node.js', 'Tailwind CSS'],
      },
      {
        category: 'Databases & Cloud',
        items: ['PostgreSQL & Supabase', 'Vector Databases (Chroma/Pinecone)', 'Docker', 'Git / GitHub CI/CD'],
      },
    ],
    featuredProjects: [
      {
        id: 'demo-proj-1',
        title: 'Student Digital Twin Career OS',
        role: 'Founder & Lead AI Engineer',
        description: 'Full-stack AI Career Operating System turning student signals into actionable readiness scoring and gap remediation vectors.',
        techStack: ['React', 'TypeScript', 'Tailwind CSS', 'FastAPI', 'Supabase', 'Gemini AI', 'Vector DB'],
        architecture: 'Client-side SPA with resilient serverless AI orchestration, vector cosine similarity matching, and Supabase metadata persistence.',
        githubUrl: 'https://github.com/Sricharan-Vangala/student-digital-twin',
        liveDemoUrl: 'https://student-digital-twin.demo',
        highlights: [
          'Engineered multi-vector readiness diagnostics calibrated against 500+ tech job specs',
          'Integrated ATS resume builder and live evidence auditing',
          'Achieved sub-200ms cached twin state restoration',
        ],
      },
      {
        id: 'demo-proj-2',
        title: 'Autonomous LLM Agent Research Suite',
        role: 'Machine Learning Researcher',
        description: 'Multi-agent reasoning harness with dynamic tool calling, self-critique loops, and persistent vector memory.',
        techStack: ['Python', 'PyTorch', 'HuggingFace', 'FastAPI', 'LangChain', 'ChromaDB'],
        architecture: 'Hierarchical planner-actor architecture with automated evaluator reflection.',
        githubUrl: 'https://github.com/Sricharan-Vangala/autonomous-llm-agent-suite',
        highlights: [
          'Implemented hierarchical memory retrieval with RAG',
          'Reduced agent task hallucination rates by 42%',
        ],
      },
      {
        id: 'demo-proj-3',
        title: 'Neural Code Synthesis & Vulnerability Auditor',
        role: 'Lead Developer',
        description: 'AST-aware semantic code auditor flagging security vulnerabilities and performance bottlenecks in real time.',
        techStack: ['Python', 'Transformers', 'Tree-sitter', 'TypeScript', 'Docker'],
        architecture: 'Abstract Syntax Tree parser paired with fine-tuned code-BERT models.',
        githubUrl: 'https://github.com/Sricharan-Vangala/neural-code-auditor',
        highlights: [
          'Parsed 100k+ lines of code across 12 languages',
          'Integrated automated GitHub Actions webhook pipeline',
        ],
      },
    ],
    achievements: [
      {
        id: 'demo-ach-1',
        title: 'Top 1% Smart India Hackathon Finalist',
        organization: 'Ministry of Education, Govt. of India',
        date: '2023-12-18',
        description: 'Developed an automated curriculum-to-competency translation platform using transformer networks.',
      },
      {
        id: 'demo-ach-2',
        title: 'Marwadi University Top Tech Innovator Recognition',
        organization: 'Marwadi University Department of CSE',
        date: '2024-01-10',
        description: 'Recognized for exceptional engineering projects in generative AI systems and student career readiness tools.',
      },
      {
        id: 'demo-ach-3',
        title: 'Deep Learning Specialization Certified',
        organization: 'DeepLearning.AI & Coursera',
        date: '2023-11-20',
        description: 'Mastered neural network architectures, hyperparameter tuning, sequence models, and deep learning math foundations.',
      },
    ],
    careerGoals: [
      {
        targetRole: 'AI/ML Engineer',
        timeline: 'By 2027 (Expected Graduation)',
        targetCompanies: ['Google', 'DeepMind', 'Microsoft', 'OpenAI', 'Top Tech Startups'],
      },
    ],
    socialLinks: {
      githubUrl: 'https://github.com/Sricharan-Vangala',
      linkedinUrl: 'https://linkedin.com/in/sricharan-vangala',
      email: 'vangalasricharan7@gmail.com',
      phone: '+91 85209 81574',
    },
    generatedAt: '2024-01-15T00:00:00.000Z',
    lastUpdatedAt: '2024-01-15T00:00:00.000Z',
  },
  updatedAt: '2024-01-15T00:00:00.000Z',
};

export const DEMO_USER_PROFILE: UserProfile = {
  id: 'demo-creator-showcase',
  email: 'vangalasricharan7@gmail.com',
  fullName: 'Sricharan Vangala',
  university: 'Marwadi University',
  degree: 'B.Tech',
  branch: 'Computer Science & Engineering (AI/ML)',
  program: 'B.Tech Computer Science & Engineering (AI/ML)',
  year: '2nd Year',
  expectedGraduationYear: '2027',
  careerGoal: 'AI/ML Engineer',
  targetRole: 'AI/ML Engineer',
  currentSkills: 'Python, PyTorch, Transformers, TypeScript, React, Scikit-Learn, Vector DB, FastAPI, Supabase, LLM Agents',
  skills: [
    'Python',
    'PyTorch',
    'Transformers',
    'TypeScript',
    'React',
    'Scikit-Learn',
    'Vector DB',
    'FastAPI',
    'Supabase',
    'LLM Agents',
  ],
  bio: 'Student engineer at Marwadi University specializing in AI/ML systems, Generative AI agent architectures, and career intelligence ontologies.',
  githubUrl: 'https://github.com/Sricharan-Vangala',
  linkedinUrl: 'https://linkedin.com/in/sricharan-vangala',
  phone: '+91 85209 81574',
  location: 'Gujarat, India',
  plan: 'pro',
  subscriptionStatus: 'active',
  portfolio: DEMO_PORTFOLIO_RECORD,
  isOnboarded: true,
  createdAt: '2024-01-15T00:00:00.000Z',
  isDemo: true,
};

export const DEMO_STUDENT_PROFILES: StudentProfile[] = [
  {
    id: 'demo-student-sricharan',
    userId: 'demo-creator-showcase',
    name: 'Sricharan Vangala',
    university: 'Marwadi University',
    degree: 'B.Tech',
    branch: 'Computer Science & Engineering (AI/ML)',
    year: '2nd Year',
    expectedGraduationYear: '2027',
    careerGoal: 'AI/ML Engineer',
    targetRole: 'AI/ML Engineer',
    currentSkills: 'Python, PyTorch, Transformers, TypeScript, React, Scikit-Learn, Vector DB, FastAPI, Supabase, LLM Agents',
    bio: 'Student engineer at Marwadi University specializing in AI/ML systems, Generative AI agent architectures, and career intelligence ontologies.',
    githubUrl: 'https://github.com/Sricharan-Vangala',
    linkedinUrl: 'https://linkedin.com/in/sricharan-vangala',
    isActive: true,
    profileData: {
      bio: 'Student engineer at Marwadi University specializing in AI/ML systems, Generative AI agent architectures, and career intelligence ontologies.',
      githubUrl: 'https://github.com/Sricharan-Vangala',
      linkedinUrl: 'https://linkedin.com/in/sricharan-vangala',
      phone: '+91 85209 81574',
      location: 'Gujarat, India',
    },
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
];

export const DEMO_SKILLS: SkillItem[] = [
  {
    id: 'demo-skill-1',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Python',
    category: 'Programming',
    proficiency: 'Expert',
    score: 95,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-2',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'PyTorch',
    category: 'AI/ML',
    proficiency: 'Advanced',
    score: 90,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-3',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Transformers & NLP',
    category: 'AI/ML',
    proficiency: 'Advanced',
    score: 88,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-4',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Generative AI & LLM Agents',
    category: 'AI/ML',
    proficiency: 'Advanced',
    score: 92,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-5',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'TypeScript',
    category: 'Programming',
    proficiency: 'Advanced',
    score: 90,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-6',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'React',
    category: 'Web Development',
    proficiency: 'Advanced',
    score: 88,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-7',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'FastAPI',
    category: 'Web Development',
    proficiency: 'Intermediate',
    score: 85,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-8',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'PostgreSQL & Supabase',
    category: 'Databases',
    proficiency: 'Advanced',
    score: 86,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-9',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Vector DB & Embeddings',
    category: 'Databases',
    proficiency: 'Intermediate',
    score: 84,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-10',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'DSA & Graph Algorithms',
    category: 'DSA',
    proficiency: 'Advanced',
    score: 88,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-11',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Git & CI/CD Pipelines',
    category: 'Tools',
    proficiency: 'Advanced',
    score: 90,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-skill-12',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    skillName: 'Deep Learning & Math Foundations',
    category: 'AI/ML',
    proficiency: 'Advanced',
    score: 90,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
];

export const DEMO_PROJECTS: ProjectItem[] = [
  {
    id: 'demo-proj-sdt',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Student Digital Twin OS',
    description:
      'Continuous student career readiness operating system synthesizing academic trajectory, project proofs, and market qualification models with automated ATS auditing and repository telemetry.',
    architecture:
      'Modular React + TypeScript client with Tailwind CSS, Supabase PostgreSQL data persistence, Google Gemini API intelligence layer, and graph ontology models.',
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Supabase', 'Gemini AI', 'Graph Ontologies'],
    githubUrl: 'https://github.com/Sricharan-Vangala/student-digital-twin',
    liveDemoUrl: 'https://student-digital-twin.vercel.app',
    role: 'Founder & Lead Architect',
    difficulty: 'Production',
    status: 'Completed',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-proj-agent',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Autonomous LLM Agent Pipeline',
    description:
      'Deep reasoning agentic pipeline executing multi-step retrieval, code execution verification, and structured report synthesis.',
    architecture:
      'FastAPI microservice backend with PyTorch embeddings, Pinecone vector indexing, tool calling orchestration, and Docker deployment.',
    techStack: ['Python', 'PyTorch', 'Transformers', 'FastAPI', 'Pinecone', 'Docker'],
    githubUrl: 'https://github.com/Sricharan-Vangala/autonomous-llm-agent',
    liveDemoUrl: 'https://github.com/Sricharan-Vangala/autonomous-llm-agent',
    role: 'AI/ML Engineer',
    difficulty: 'Advanced',
    status: 'Completed',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-proj-graph',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Neural Graph Academic Knowledge Engine',
    description:
      'Dynamic knowledge graph system mapping university academic syllabi to high-demand industry skill clusters and placement competencies.',
    architecture:
      'NetworkX and PyTorch Geometric graph embeddings mapped to Neo4j knowledge triples with semantic similarity scoring.',
    techStack: ['Python', 'NetworkX', 'PyTorch Geometric', 'Neo4j', 'Scikit-Learn'],
    githubUrl: 'https://github.com/Sricharan-Vangala/neural-graph-knowledge',
    liveDemoUrl: 'https://github.com/Sricharan-Vangala/neural-graph-knowledge',
    role: 'Lead Developer',
    difficulty: 'Advanced',
    status: 'Completed',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-proj-resume',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'ATS Smart Resume Optimizer & Placement Simulator',
    description:
      'Deterministic parser and semantic embedding scorer analyzing technical resumes against role benchmarks with real-time actionable feedback.',
    architecture:
      'Client-side PDF text extraction and semantic keyword density matcher with structured scoring algorithms.',
    techStack: ['TypeScript', 'React', 'Node.js', 'NLP Embeddings', 'Tailwind CSS'],
    githubUrl: 'https://github.com/Sricharan-Vangala/ats-resume-optimizer',
    liveDemoUrl: 'https://github.com/Sricharan-Vangala/ats-resume-optimizer',
    role: 'Full Stack AI Developer',
    difficulty: 'Intermediate',
    status: 'Completed',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
];

export const DEMO_ACHIEVEMENTS: AchievementItem[] = [
  {
    id: 'demo-ach-1',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Built and Launched Student Digital Twin OS',
    organization: 'Marwadi University Showcase & Open Source',
    date: '2024-02-01',
    description:
      'Designed and deployed full-stack Student Digital Twin platform empowering engineering students with AI-driven readiness telemetry.',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-ach-2',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Marwadi University Top Tech Innovator Recognition',
    organization: 'Marwadi University Department of CSE',
    date: '2024-01-10',
    description:
      'Recognized for exceptional engineering projects in generative AI systems and student career readiness tools.',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-ach-3',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Deep Learning Specialization Certified',
    organization: 'DeepLearning.AI & Coursera',
    date: '2023-11-20',
    description:
      'Mastered neural network architectures, hyperparameter tuning, sequence models, and deep learning math foundations.',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 'demo-ach-4',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    title: 'Open Source AI Contributor & Project Lead',
    organization: 'GitHub Community',
    date: '2024-03-01',
    description:
      'Published open-source AI tooling, autonomous agent prototypes, and automated evaluation frameworks.',
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
];

export const DEMO_CAREER_GOALS: CareerGoalItem[] = [
  {
    id: 'demo-goal-1',
    userId: 'demo-creator-showcase',
    studentProfileId: 'demo-student-sricharan',
    goal: 'Become a Principal AI/ML Engineer & Systems Architect',
    targetRole: 'AI/ML Engineer',
    targetCompanies: ['Google', 'DeepMind', 'Microsoft', 'OpenAI', 'Top Tech Startups'],
    requiredSkills: [
      'PyTorch',
      'Distributed Machine Learning',
      'LLM Reasoning',
      'System Design',
      'Vector Ontologies',
    ],
    timeline: 'By 2027 (Expected Graduation)',
    isActive: true,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z',
  },
];
